name: website-cinemix-dev

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cinemix}
      POSTGRES_USER: ${POSTGRES_USER:-cinemix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cinemix}
      TZ: Europe/Lisbon
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cinemix} -d ${POSTGRES_DB:-cinemix}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-backend.config.settings}
      DATABASE_URL: ${DATABASE_URL:-postgres://cinemix:cinemix@db:5432/cinemix}
      PYTHONUNBUFFERED: "1"
      APP_ENV: dev
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-cinemix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cinemix}
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    working_dir: /code
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8765:8000"
    command: >
      sh -c "
        echo 'A aguardar que a DB esteja healthy (via depends_on)...'
        
        echo 'A correr migrações...'
        python manage.py migrate --no-input

        echo 'A iniciar Django runserver (DEV)...'
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8765}
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules # Protege a pasta de instalação do npm
    # --- CORREÇÃO FINAL: Forçar a reinstalação e iniciar o servidor ---
    command: >
      sh -c "
        npm install && npm run dev
      "
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"

volumes:
  db_data:
  static_volume:
  media_volume:
