services:
  backend:
    environment:
      APP_ENV: prod
      DEBUG: "0"
    volumes:
      - static_data:/code/staticfiles
    command: >
      sh -c "/code/entrypoint.sh"
    expose:
      - "8000"

  web:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
      target: prod
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - static_data:/static:ro

volumes:
  static_data: